version: 2
jobs:
  deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh rootR@$103.130.213.12
             "cd /var/www/html/tabu"
             "git pull"
workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           requires:
           filters:
             branches:
               only: master # only deploy on the master branch
