 version: 2.1
 
 executors:
   default:
     docker:
        - image: 'cimg/node:16.11.1'
 jobs:
   deploy:
     executor: default
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
           no_output_timeout: 30s
       - telegram-orb/notification
 orbs:
   telegram-orb: pkb/telegram-orb@0.1.0
 workflows:
   deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy master branchh
       
