 version: 2.1

 jobs:
   noti_success:
     docker:
       - image: 'circleci/node:10'
     steps:
       - telegram/notify:
           message: Build Successfully.
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
 orbs: # adds orbs to your configuration
   telegram: woltsu/telegram@0.0.9
 workflows:
   noti:
     requires:
       - deploy
     when: on_success
     jobs:
       - noti_success
   deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy master branch
