 version: 2.1

 jobs:
   build:
     docker:
       - image: 'cimg/base:stable'
     steps:
       - run: echo "hello"
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
 orbs: # adds orbs to your configuration
   jira: circleci/jira@1.0.5
 workflows:
   version: 2.1
   build:
    jobs:
      - build:
          post-steps:
            - jira/notify
   deploy:
     jobs:
       - deploy:
           post-steps:
             - jira/notify:
               environment_type: development
               job_type: deployment
           filters:
             branches:
               only: master # only deploy on the main branch
