 version: 2.1

 jobs:
   build:
     docker:
       - image: 'circleci/node:10'
     steps:
       - telegram/notify:
           message: Build Successfully.
           
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
           no_output_timeout: 30s
 orbs: # adds orbs to your configuration
   telegram: woltsu/telegram@0.0.9
 workflows:
   deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy master branchh
       - build:
           requires:
             - deploy
       
