 version: 2.1
 
 jobs:
   build:
     #...
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh roott@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
           no_output_timeout: 30s
       - telegram-orb/status
 orbs:
   telegram-orb: pkb/telegram-orb@0.1.0
 workflows:
   deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy master branch
       
