 version: 2

 jobs:
   build:
     #...
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "php -v"

 workflows:
   version: 2
   build-and-deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy on the main branch
