version: 2
jobs:
  # These commands are triggered only after a successful (green) build.
 deployment:
   dev:
     branch: master
     commands:
       - ssh root@103.130.213.12 'cd /var/www/html/tabu && git pull origin master'
