 version: 2.1
 
 jobs:
   build:
    #..
   deploy:
     docker:
       - image: 'cimg/node:16.11.1'
     machine:
       enabled: true
     steps:
       - checkout
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
           no_output_timeout: 30s
       - run: exit 0
       - telegram-orb/status:
          fail_only: false
          only_for_branches: master
 orbs:
   telegram-orb: pkb/telegram-orb@0.1.0
 workflows:
   deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy master branch
       
