 version: 2.1

 jobs:
   build:
     docker:
       - image: 'circleci/node:10'
     steps:
       - telegram/sendsticker:
           telegram-sticker: >-
             https://raw.githubusercontent.com/TelegramBots/book/master/src/docs/sticker-fred.webp
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
 orbs: # adds orbs to your configuration
   telegram: woltsu/telegram@0.0.9
 workflows:
   build:
    jobs:
      - build
   deploy:
     jobs:
       - deploy:
           filters:
             branches:
               only: master # only deploy master branch
