 version: 2.1
 
 jobs:
   build:
    docker:
      - image: 'cimg/node:16.11.1'
    steps:
      - run:
           command: |
             curl ${TELEGRAM_WEBHOOK}"/sendMessage?chat_id="${TELEGRAM_GROUPID}"&text=test"
           name: Telegram - Setting Success Condition
#       - checkout
#       - run: exit 0
#       - telegram-orb/status:
#          channel: "1333389399"
#          success_message: "Successfully"
#          failure_message: "Error"
#          webhook: "https://api.telegram.org/bot5399404697:AAGDtkC58-d5mr3Dba5bXLmwkrO-5Q9-r3s"
#          only_for_branches: master
   deploy:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh root@103.130.213.12 "cd /var/www/html/tabu && git pull origin master"
             TEXT="Deployment!!!"
             TEXT=TEXT"Status"
           no_output_timeout: 30s
       - run:
           command: |
             curl ${TELEGRAM_WEBHOOK}"/sendMessage?chat_id="${TELEGRAM_GROUPID}"&text="${TEXT}"success"
           name: Telegram - Setting Success Condition
           when: on_success
       - run:
           command: |
             curl ${TELEGRAM_WEBHOOK}"/sendMessage?chat_id="${TELEGRAM_GROUPID}"&text=error"
           name: Telegram - Setting Error Condition
           when: on_fail
#  orbs:
#    telegram-orb: pkb/telegram-orb@0.1.0
 workflows:
   deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build
           filters:
             branches:
               only: master # only deploy master branch
       
